2024-09-30 03:27:58,912 INFO    MainThread:68480 [wandb_setup.py:_flush():79] Current SDK version is 0.18.2
2024-09-30 03:27:58,912 INFO    MainThread:68480 [wandb_setup.py:_flush():79] Configure stats pid to 68480
2024-09-30 03:27:58,912 INFO    MainThread:68480 [wandb_setup.py:_flush():79] Loading settings from C:\Users\a_ryz\.config\wandb\settings
2024-09-30 03:27:58,913 INFO    MainThread:68480 [wandb_setup.py:_flush():79] Loading settings from C:\Users\a_ryz\PycharmProjects\MNIST_Anna\src\wandb\settings
2024-09-30 03:27:58,913 INFO    MainThread:68480 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-09-30 03:27:58,913 INFO    MainThread:68480 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'src\\train.py', 'program_abspath': 'C:\\Users\\a_ryz\\PycharmProjects\\MNIST_Anna\\src\\train.py', 'program': 'C:\\Users\\a_ryz\\PycharmProjects\\MNIST_Anna\\src\\train.py'}
2024-09-30 03:27:58,913 INFO    MainThread:68480 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-09-30 03:27:58,913 INFO    MainThread:68480 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-09-30 03:27:58,913 INFO    MainThread:68480 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-09-30 03:27:58,913 INFO    MainThread:68480 [wandb_init.py:_log_setup():532] Logging user logs to C:\Users\a_ryz\PycharmProjects\MNIST_Anna\src\wandb\run-20240930_032758-b9vfg1lo\logs\debug.log
2024-09-30 03:27:58,914 INFO    MainThread:68480 [wandb_init.py:_log_setup():533] Logging internal logs to C:\Users\a_ryz\PycharmProjects\MNIST_Anna\src\wandb\run-20240930_032758-b9vfg1lo\logs\debug-internal.log
2024-09-30 03:27:58,914 INFO    MainThread:68480 [wandb_init.py:init():616] calling init triggers
2024-09-30 03:27:58,914 INFO    MainThread:68480 [wandb_init.py:init():623] wandb.init called with sweep_config: {}
config: {}
2024-09-30 03:27:58,914 INFO    MainThread:68480 [wandb_init.py:init():666] starting backend
2024-09-30 03:27:58,914 INFO    MainThread:68480 [wandb_init.py:init():670] sending inform_init request
2024-09-30 03:27:58,919 INFO    MainThread:68480 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2024-09-30 03:27:58,919 INFO    MainThread:68480 [wandb_init.py:init():683] backend started and connected
2024-09-30 03:27:58,930 INFO    MainThread:68480 [wandb_init.py:init():778] updated telemetry
2024-09-30 03:27:58,990 INFO    MainThread:68480 [wandb_init.py:init():811] communicating run to backend with 90.0 second timeout
2024-09-30 03:27:59,169 ERROR   MainThread:68480 [wandb_init.py:init():837] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-09-30 03:27:59,169 ERROR   MainThread:68480 [wandb_init.py:init():1261] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\a_ryz\PycharmProjects\MNIST_Anna\.venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 1251, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\a_ryz\PycharmProjects\MNIST_Anna\.venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 843, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-09-30 03:27:59,758 WARNING MsgRouterThr:68480 [router.py:message_loop():77] message_loop has been closed
